<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <?php echo $this->getChildHtml('header'); ?>
        </div>  
        <div id="contents"> 
            <?php echo $this->getChildHtml('slider'); ?>       
            <?php echo $this->getChildHtml('content'); ?>
        </div>
        <div id="footer">
            <?php echo $this->getChildHtml('footer'); ?>
        </div>
    </div>
</body>
</html>

