<?php
/**
 * Custom tab exepreview template
 */

?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Exe Preview Information (<?php echo "Prodcut ID: ".$product_id; ?> , <?php echo "Lesson ID: ".$lesson_id;?>)</h4>
    </div>
    
    <div class="fieldset fieldset-wide">
       <div class="hor-scroll">
        <?php 
        echo "<h1>title</h1>";
        
        $exeLoadFile = 'vocabulary.phtml';
        include_once './vocabulary.phtml';
        
        
        ?>
        
        
        
       </div>
    </div>
</div>