<?php
/**
 * Custom Import lesson template
 */
echo $this->getUrl();
?>
<h1>Import lessons.</h1>
<div>
<form action="<?php echo $this->getUrl('*/lesson_import/process') ?>" method="post" enctype="multipart/form-data">
<label for="file">Filename:</label>
<input type="file" name="file" id="file"><br>
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey()?>" >
<input type="submit" name="submit" value="Submit">
</form>
</div>
