
	<div class="footer01">
		<ul>
			<li><a href="<?php echo Mage::getBaseUrl().'terms';?>">・利用規約</a></li>
			<li><a href="<?php echo Mage::getBaseUrl().'privacy';?>">・プライバシー</a></li>
			<li><a href="<?php echo Mage::getBaseUrl().'tokusyo';?>">・特商法</a></li>　　
			<li><a href="<?php echo Mage::getBaseUrl().'contacts';?>">・お問合せ</a></li>　　
			<li><a href="<?php echo Mage::getBaseUrl().'staff';?>">・運営メンバ</a></li>
			<li><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'blog';?>"  target="_blank">・ブログ</a></li>
		</ul>
		<div>Copyright © 2013 CO.,LTD. All rights Reserved</div>
	</div>
