<div id="main01">
	<div id="main_center">
		<div id="main_left">
			<div id="person" class="box">	
				<img src="<?php echo $this->getSkinUrl('images/person01.png');?>" />
			</div>
			<div id="words" class="box">
				<h2>いつ中国語を勉強するの!?<br /><span class="words_large">今でしょ！</span></h2>
				<p>モバイル中国語教室ならPC・スマホでいつでもどこでも効率よく中国語の学習が出来ます。</p>
				<div id="btn_reg"><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">まずは無料登録</a></div>
			</div>
		</div>
		<div id="main_right">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('slider')->toHtml() ?>
		</div>
	</div>
	<div id="main_bottom">
	</div>
</div><!--End main01-->
<div id="main02">
	<h2>サイトの特徴！</h2>
	<div class="circle">
		<img src="<?php echo $this->getSkinUrl('images/circle01.png');?>" />
		<h3>いつでもどこでも中国語学習</h2>
		<p>PCだけでなくタブレット・スマートフォン（iphone/ipad/android）でいつでもどこでも学習可能。仕事が忙しく中国語教室に通えない方にも最適！</p>
	</div>
	<div class="circle">
		<img src="<?php echo $this->getSkinUrl('images/circle02.png');?>" />
		<h3>効率の良い学習コンテンツ</h2>
		<p>一般的な中国語教室と同様にサイト内のテキスト（課文）にそって学習を行います。課文・単語・文法・練習とサイト内で効率よく学習していくことが可能です。</p>
	</div>
	<div class="circle">
		<img src="<?php echo $this->getSkinUrl('images/circle03.png');?>" />
		<h3>豊富なコンテンツと機能</h2>
		<p>毎週新しいコンテンツが増えていくので飽きずに学習を続けていくことだ出来ます。またテキストのピンイン、翻訳の表示・非表示など便利な機能も豊富！</p>
	</div>
</div><!--End main03-->
<div id="squares_area">
	<h2>中国語学習の背景</h2>
	<div class="square">
		<img src="<?php echo $this->getSkinUrl('images/square01.jpg');?>" />
		<div class="square_text">
			<h3>中国語の必要性</h2>
			<p>　経済産業省の日本企業約4,000社を対象にしたアンケートによると海外における今後の最重要拠点について中国が欧米諸国を大きく引き離してトップとなっています。中国語を話せる日本人の需要が高まっており、習得しておけば就職や転職に有利といえます。</p>
		</div>
	</div>
	<div class="square">
		<img src="<?php echo $this->getSkinUrl('images/square02.jpg');?>" />
		<div class="square_text">
			<h3>日本人に有利な中国語</h2>
			<p>　日本では日本語の中で2136字もの漢字を常用漢字として採用しており、中国では2500字の漢字が常用字として指定されています。<br>
			　完全に重複する訳ではありませんが、母語で漢字を使う日本人が他の国の人に比べて非常に有利と言えます。</p>
		</div>
	</div>
	<div class="square">
		<img src="<?php echo $this->getSkinUrl('images/square03.jpg');?>" />
		<div class="square_text">
			<h3>国内の中国語学習状況</h2>
			<p>　日本では中国語の学習人口は増加の一途を辿っており、200万人を突破したと言われています。<br>
			　また学校現場でも文部科学省の調査で英語以外の外国語を開設する高等学校等で中国語を開設する高校が最も多くなっています。</p>
		</div>
	</div>
</div><!--End main03-->




