<?php 
/**
 * Calling type1 function from Exe Obj
 * @return Array
 * sample: Array ( [0] => Array ( [source] => 你好 [target] => こんにちは [pinyin] => ni3 hao3 )
 *                 [1] => Array ( [source] => 我 [target] => 私 [pinyin] => wo3 ) 
 *                 [2] => Array ( [source] => 叫 [target] => ～という [pinyin] => jiao4 ) 
 *                 [3] => Array ( [source] => 李明 [target] => 李明 [pinyin] => li3 ming2 ) )
 */
$lessonId = $this->getProductId();
// Initialise ExeType model
$exeM = Mage::getModel('lesson/jpexetype');
// Set lesson id
$exeM->setLessonId($this->getProductId());
$type2 = $exeM->getType(2);
// Return all source only from type 1
$type2_source = $exeM->getSourceArr($type2,2);
// Return random source as the first source
$type2_ran_source = $exeM->getRandomSource($type2_source);
// Return all audio url array only from type 2
$type2_audio = $exeM->getAudioArr($type2_source, $type2_ran_source, $lessonId);
?>
<script>
$( document ).ready(function() {
var sinoApp = sinoApp || {};

// Flashcard will be the default exercise, other exercise will 
// have different names
sinoApp.exe_flashcard_type2 = function() {
    	
    //var questions = new Array("你好","我","叫","李明");
    // Defline player
        audio1 = $('#exe_audio_1');     
        player = audio1[0]; 
    	var listenText = " 再生 > ";
        <?php echo 'var questions = '.json_encode($type2_source).';'; ?>
        <?php echo 'var questionsAudioUrl = '.json_encode($type2_audio).';'; ?>
        totalOrigin = questions.length;
 
    ifc =  $('#exe_image_frame_container'); 
    image_frame = $('.exe_image_frame');  
   
    image_frame.click(function (e) {     
          
          // find out question value
          qValue = $('#exe_display_question').attr('answer').trim();
          // find out selected value
          value = $(this).attr('answer').trim();
          wrapper = $(this).parent();
          // compare question value and answer value, if equal change
          // next question value
          if(value==qValue){ 
             // use green color to highlight the correct answer
             wrapper.addClass("exe_image_frame_green");
             setTimeout(function(){
            	 wrapper.removeClass("exe_image_frame_green");}, 500);             
             // find out the position of given Q in the array
             total = questions.length;
             var i=0; var spot;
             while(i<total){
                if(questions[i]==qValue ) { spot = i; }
                i++;
             }

             questions.splice(spot,1); 
             questionsAudioUrl.splice(0,1); 
             serialNum = totalOrigin - (total-2);  
            
              if(total-1>0){       
            	  $('#exe_display_question').attr('answer',questions[0].trim());
            	  $('#exe_display_question_indicator').text(listenText+serialNum);
                  player.src = questionsAudioUrl[0];
                  
              } else {
                  $('#exe_display_question').hide();
                  $('.exe_continue_next').show();
              }
          } else {
               // incorrect answer
               // First to update the score by using ajax to update session
               score = 1;
               var dataString = 'score=' + score;
               $.ajax({
                        type: "POST",
                        url: '<?php echo $this->getUrl("chinese-lesson/index/saveScore") ?>',
                        data: dataString,
                        cache: false,
                        //success: function(response) { alert('ok'); }
               });
               
               wrapper.addClass("exe_image_frame_red");
               wrapper.animate({left:'-10px'},100)
                      .animate({left:'10px'},100)
                      .animate({left:'0px'},100);
               setTimeout(function(){
                      wrapper.removeClass("exe_image_frame_red");}, 500);      
          }            
   }); // finish click event  
   
   exe_play_question =  $('#exe_play_question'); 
   exe_play_question.click(function (e) {     
	  player.volume = .50; 
      player.load();
      player.play();
  
   }); // finish question_play click event  
};


 
sinoApp.exe_flashcard_type2();


});
</script>

<div id="exe_container">
    <!-- Display audio container -->
   <div class="exe_audio_container">
        <audio id="exe_audio_1" preload="auto" tabindex="0" controls="" type="audio/mpeg">
        <source id="exe_audio_1_source" type="audio/mp3" src="<?php echo $type2_audio[0]; ?>"></source>Sorry, your browser does not support HTML5 audio.</audio>
    </div>
    <!-- Display exe image container -->
    <div id="exe_image_frame_container" class="exe_image_frame_container">
        <p class="exe_type_title"><?php echo $exeM->getTypeTitle(2); ?></p>
        <?php  //echo "<h1>lesson: ".$exeM->lesson_id."</h1>"; echo "<h1>current_product: ".Mage::registry('current_product')."</h1>";
        foreach($type2_source as $type2_source_v) { 
       	       $type2_target  = $exeM->getValueFromSource($type2_source_v, $type2, 'target');
       	       $type2_pinyin  = $exeM->getValueFromSource($type2_source_v, $type2, 'pinyin');
       	       $type2_ran_uid = $exeM->getValueFromSource($type2_source_v, $type2, 'uid');
       	       $type_img_path = $exeM->getTypeResource($type2_ran_uid);        
       	?>
       
            <div class="exe_image_frame_wrapper">
            <div class="exe_image_frame" answer="<?php echo $type2_source_v; ?>" >
                <div class="exe_image_inner_frame">
                    <p><?php echo $type2_source_v; ?></p>
                    <p class="exe_image_inner_frame_pinyin"><?php echo Mage::helper('lesson/pinyin')->converPinyinNumberToToneMark($type2_pinyin); ?></p>
                </div>
            </div>
            </div>
              
         <?php 
         }
         ?>
    </div>   
   <div class="exe_question_container">
        <div id="exe_display_question" class="exe_display_question" answer="<?php echo $type2_ran_source;?>">   
           
                <button type="button" id="exe_play_question" >
                    <img src="<?php echo $this->getSkinUrl('images/speaker.gif');?>" alt="speaker" > 
                    <span id="exe_display_question_indicator"> 再生 > 1</span> 
                </button>
            
        </div>
    </div>  
</div><!-- finish exe_contaier -->    