<div id="sidebar01">
	<ul id="menu">
		<li class="menu_title"><div>レッスンレベル</div></li>
		<li class="menu_active"><a href="#"><img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /> 入門<span class="menu_detail">挨拶レベル</span></a>
			<ul class="sub">
				<li><a href="#">レッスン1</a></li>
				<li><a href="#">レッスン2</a></li>
			</ul>
		</li>
		<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /> 初級<span class="menu_detail">日常会話(下)レベル</span></a>
			<ul class="sub">
				<li><a href="#">レッスン1</a></li>
				<li><a href="#">レッスン2</a></li>
			</ul>
		</li>
		<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /> 中級<span class="menu_detail">日常会話(上)レベル</span></a>
			<ul class="sub">
				<li><a href="#">レッスン1</a></li>
				<li><a href="#">レッスン2</a></li>
			</ul>
		</li>
		<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /> 高級<span class="menu_detail">ビジネスレベル</span></a>
		</li>
	</ul>
</div>
		
		
		
		
		
		
		
		
		
		
		
		
		