<?php 
// 3 is the id of learnlan, all categories are under learnlan
 $_category = Mage::getModel('catalog/category')->load(3);    
    $_categories = $_category
                    ->getCollection()
                    ->addAttributeToFilter('is_active', 1)
                    ->addAttributeToSelect(array('name', 'description', 'url_key'))
                    ->addIdFilter($_category->getChildren());

 // get current category ID, if current_category is not available return root category id, which is also OK
$currentCatId = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
?>
<div id="sidebar01">
	<ul id="menu">
		<li class="menu_title"><div>レッスンレベル</div></li>
		<?php 
		/**
		 * @todo $_category is the parent of sessions, for the time being only session 1 is been used,
		 * in the future if we want to add more session under parent category, we need to give a link to a particular session rather than loop
		 * through session`s parent category, just take a note
		 */
		?>
		<?php foreach ($_categories as $_category): ?>
		<li <?php if($currentCatId == $_category->getId()){ echo 'class="menu_active"'; } ?>>
		    <!-- enable category beginner(4) and primary(5) -->
		    <?php $allowedPublishCateId = array('4','5') ?>
		    <?php if(in_array($_category->getId(), $allowedPublishCateId)):?>
		    <a href="<?php echo $this->getCategoryUrl($_category); ?>"><img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /><?php echo $_category->getName();?>
		    <span class="menu_detail"><?php echo $_category->getDescription(); ?></span></a>	
		    <?php else:?>
		    <img src="<?php echo $this->getSkinUrl('images/list_style.png');?>" /><?php echo $_category->getName();?>
		    <span class="menu_detail"><?php echo $_category->getDescription(); ?></span><span class="comingsoon"><img src="<?php echo $this->getSkinUrl('images/comingsoon.png');?>" /></span>	
		    <?php endif;?>
		</li>
		<?php endforeach;?>
	</ul>
</div>
